# Generated by Django 4.2.2 on 2023-06-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyChainEvents', '0002_alter_eventstatus_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstatus',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='description',
            field=models.TextField(verbose_name=2),
        ),
    ]
