# Generated by Django 4.2.2 on 2023-06-28 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_supplychainitem_price_and_more'),
        ('supplyChainEvents', '0005_alter_supplychainevent_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplychainevent',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_chain_item', to='products.supplychainitem'),
        ),
    ]
