# Generated by Django 4.2.2 on 2023-06-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyChainEvents', '0007_alter_eventstatus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstatus',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='supplychainevent',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
