# Generated by Django 4.2.2 on 2023-06-21 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_supplychainitem_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplychainitem',
            name='id',
            field=models.AutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
