# Generated by Django 4.2.2 on 2023-06-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_supplychainitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplychainitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='supplychainitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
