# Generated by Django 4.2.2 on 2023-06-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_supplychainitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplychainitem',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
